---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
---
apiVersion: v1
kind: Secret
metadata:
  name: actions-runner-system
  namespace: actions-runner-system
type: Opaque
# stringData:
#   github_token: "token"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: actions-runner-controller
  namespace: kube-system
spec:
  chart: actions-runner-controller
  repo: https://actions-runner-controller.github.io/actions-runner-controller
  version: 0.15.0
  targetNamespace: actions-runner-system
  valuesContent: |-
    resources:
      requests:
        memory: "128Mi"
        cpu: "0.25"
      limits:
        memory: "256Mi"
        cpu: "2.00"
    authSecret:
      name: actions-runner-system
    syncPeriod: 1m
