---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: trinity-roguelike-ci
  namespace: default
spec:
  ephemeral: false
  repository: yoangau/trinity-roguelike
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: trinity-roguelike-ci
  serviceName: trinity-roguelike-ci
  template:
    metadata:
      labels:
        app: trinity-roguelike-ci
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: trinity-roguelike-ci
  namespace: default
spec:
  scaleTargetRef:
    name: trinity-roguelike-ci
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - trinity-roguelike-ci
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: pholi-ci
  namespace: default
spec:
  ephemeral: true
  repository: yoangau/pholi-server
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: pholi-ci
  serviceName: pholi-ci
  template:
    metadata:
      labels:
        app: pholi-ci
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: pholi-ci
  namespace: default
spec:
  scaleTargetRef:
    name: pholi-ci
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - yoangau/pholi-server
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: pholi-game-ci
  namespace: default
spec:
  ephemeral: true
  repository: yoangau/pholi-game
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: pholi-game-ci
  serviceName: pholi-game-ci
  template:
    metadata:
      labels:
        app: pholi-game-ci
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: pholi-game-ci
  namespace: default
spec:
  scaleTargetRef:
    name: pholi-game-ci
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - yoangau/pholi-game
