---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: trinity-roguelike-ci
  namespace: default
spec:
  ephemeral: false
  repository: yoangau/trinity-roguelike
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: trinity-roguelike-ci
  serviceName: trinity-roguelike-ci
  template:
    metadata:
      labels:
        app: trinity-roguelike-ci
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: trinity-roguelike-ci
  namespace: default
spec:
  scaleTargetRef:
    name: trinity-roguelike-ci
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - trinity-roguelike-ci
