---
apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: homer
---
apiVersion: v1
kind: Secret
metadata:
  name: homer
  namespace: default
type: Opaque
# stringData:
#   credentials: "admin:$2y$12$8KtQ4SQb6QpebcgYvMPjwOv3Jz9ojkNq8FVWZmk5q1BW9BoEX2aAy" # admin:admin by default, bcrypted password: https://bcrypt-generator.com/

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: homer
  namespace: default
spec:
  basicAuth:
    secret: "homer"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)
      kind: Rule
      services:
        - name: homer
          port: 8080
      middlewares:
        - name: homer
  tls:
    secretName: wilcard-main-domain-tls

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer
  namespace: default
data:
  config.yml: |
    ---
    title: "Dashboard"
    subtitle: "Homer"
    logo: "logo.png"

    header: true
    footer: false

    services:
      - name: "Feed"
        icon: "fas fa-rss"
        items:
          - name: "Huginn"
            logo: "https://camo.githubusercontent.com/198521c8a76f1a87b04042e7ed5ce864caf8b033ef3a655ca48cd1114291f7e4/68747470733a2f2f7261772e6769746875622e636f6d2f687567696e6e2f687567696e6e2f6d61737465722f6d656469612f687567696e6e2d6c6f676f2e706e67"
            url: "https://huginn.${DOMAIN_NAME}"

      - name: "Database"
        icon: "fas fa-database"
        items:
          - name: "pgAdmin4"
            logo: "https://www.pgadmin.org/static/docs/pgadmin4-dev/docs/en_US/_build/html/_images/logo-right-128.png"
            url: "https://pgadmin4.${DOMAIN_NAME}"

      - name: "Administration"
        icon: "fas fa-tools"
        items:
          - name: "Kubernetes"
            logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/247px-Kubernetes_logo_without_workmark.svg.png"
            url: "https://kubernetes.${DOMAIN_NAME}"
          - name: "PiHole"
            logo: "https://camo.githubusercontent.com/9426a93d32aa9f5ad757b2befcdb762a270d344efd6b8d287a2cea2c4c2233b8/68747470733a2f2f70692d686f6c652e6769746875622e696f2f67726170686963732f566f727465782f566f727465785f776974685f576f72646d61726b2e737667"
            url: "https://pihole.${DOMAIN_NAME}"

      - name: "Monitoring"
        icon: "fas fa-heartbeat"
        items:
          - name: "Traefik"
            logo: "https://github.com/traefik/traefik/raw/0a3e40332a86cc061bf16d8895b10defeb999171/docs/content/assets/img/traefik.logo.png"
            url: "https://traefik.${DOMAIN_NAME}"
          - name: "crt.sh"
            logo: "https://avatars.githubusercontent.com/u/12831199?s=200&v=4"
            url: "https://crt.sh/?q=${DOMAIN_NAME}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: homer
  namespace: default
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.25"
            limits:
              memory: "64Mi"
              cpu: "0.25"
          ports:
            - name: web
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /www/assets/config.yml
              subPath: config.yml
      volumes:
        - name: config
          configMap:
            name: homer

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: homer
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homer
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
