---
apiVersion: v1
kind: Service
metadata:
  name: pholi-server
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 3000
  selector:
    app: pholi-server

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pholi-server
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`pholi-server.${DOMAIN_NAME}`)
      kind: Rule
      services:
        - name: pholi-server
          port: 3000
  tls:
    secretName: wilcard-main-domain-tls

---
apiVersion: v1
kind: Secret
metadata:
  name: pholi-server
  namespace: default
type: Opaque
# stringData:
#   jwt_secret: "somecode"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pholi-server
  namespace: default
  labels:
    app: pholi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pholi-server
  template:
    metadata:
      labels:
        app: pholi-server
    spec:
      containers:
        - name: app
          image: ghcr.io/yoangau/pholi-server:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.25"
            limits:
              memory: "1024Mi"
              cpu: "2.00"
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pholi-server
                  key: jwt_secret
            - name: JWT_EXPIRATION
              value: "30d"
          ports:
            - name: web
              containerPort: 3000
          volumeMounts:
            - name: db
              mountPath: /db
      imagePullSecrets:
        - name: dockerconfigjson-github-com-pholi-server
      volumes:
        - name: db
          hostPath:
            path: /storage/pholi-server/db

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pholi-server
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pholi-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
